Add updated iOS App support to the Vulkan examples
SaschaWillems/Vulkan pull request #1119
Opened 2024-04-25 00:02 UTC by SRSaunders

This PR depends on and includes #1117 due to dependencies.  However, I am submitting this as a separate PR since I am not sure if you want to include this here.  I would be happy to provide support from time-to-time for new updates if you need it. I would be interested in @billhollings reaction, and if he would like this added to your repository, or if he has other plans.

Similar to before, it is an Xcode project contained within a separate sub-folder (but named _ios_ this time) that depends on the base project.  It is like the previous xcode sub-folder, but with documentation and functionality emphasis on _iOS_ and the _iOS Simulator_.  _macOS_ standalone app support is also present but not emphasized.  Most users should use the base cmake project in the main folder for _macOS_.

Details are:

1. Updated to use **VK_USE_PLATFORM_METAL_EXT** by default vs. deprecated **VK_USE_PLATFORM_IOS_MVK**
2. Updated to use **MoltenVK.xcframework** from the Vulkan SDK (recommend using SDK 1.3.275.0 or later).
3. Added support for single and multi-touch gestures on _iOS_ and the _iOS Simulator_, allowing select and rotation of the scene, plus translation and zoom.  Virtual keyboard support remains for imgui overlay toggle and animation pausing.
4. Updated example.h file with categories and comments on which examples currently work and don't work on iOS.
6. Default Xcode setting with the iOS Simulator and iPhone 15 Pro pre-selected, and the pre-processor macro shown.
5. Updated to work with your current main project baseline.
7. Updated docs.

Let me know if you are interested in this and if so, I will do my best to help out.  I realize that automated CI support is not implemented at this time, but perhaps could be added.

Here is a pic of the bloom example running on the iOS simulator...
![Screenshot 2024-04-21 at 1 26 16 PM](https://github.com/SaschaWillems/Vulkan/assets/82544213/87beac5b-665f-470f-a7b5-e7331fe0de30)

2024-04-26 15:28 UTC, SaschaWillems commented
Thank you very much for your PR. This is very much appreciated. I don't own any apple devices to test this on, so all I can do is a code review.

I will take a look at this, but it may take a few weeks.

2024-04-27 01:59 UTC, SRSaunders commented
Again thanks for agreeing to look at this.  Only the final commit (https://github.com/SaschaWillems/Vulkan/pull/1119/commits/e4a42420a21ba1424e979b84827be65754cfbd9f) is different from the other PR.

Given your comments above about testing on Apple devices, I may go ahead and add CI support so you can be assured of build sanity.

2024-05-04 14:54 UTC, SRSaunders commented
Fixed merge conflicts.

Thanks for catching my redundant code for getting `rayTracingPipelineProperties`.  I missed the common code for getting this in **VulkanRayTracingSample**.  Note as part of the merge I removed my unneeded calls to `vkGetPhysicalDeviceProperties2()` in the ray tracing examples.

2024-05-04 15:29 UTC, SaschaWillems requested changes
While I can't test this looks fine to me and CI is in place. Aside from a minor nitpick I'll merge once I get green light from @billhollings with regards to copyright.

2024-05-04 15:53 UTC, SRSaunders commented on benchmark-all-validate.py
Done...

2024-05-04 15:54 UTC, SRSaunders commented on apple/README_MoltenVK_Examples.md
> +Copyright (c) 2016-2024 [The Brenwill Workshop Ltd.](http://www.brenwill.com).
Makes sense.  And as I mentioned before, if @billhollings has concerns about maintaining it I can help out.

2024-05-21 19:24 UTC, billhollings commented on apple/README_MoltenVK_Examples.md
> +Copyright (c) 2016-2024 [The Brenwill Workshop Ltd.](http://www.brenwill.com).
Sorry for the delay. 

Yes...any code Brenwill contributes (or has contributed) is open-source, and respects the open-source license of this repo.

2024-05-21 19:27 UTC, billhollings approved these changes

2024-05-22 19:07 UTC, SaschaWillems commented
Thank you very much for the confirmation. Merging this now :)

2024-05-22 19:07 UTC, merged